baseURL = 'https://blog.lumetsberger.com/'
languageCode = 'en-us'
title = 'Moritz Lumetsberger'
theme = 'PaperMod'

[params]
env = "production"
title = "Moritz Lumetsberger"
description = "Entrepreneur who loves starting things and exploring bold ideas. Co-founder of rendersnek (3D animation studio) and FOOH.com (largest FOOH & CGI archive). Expert in AI automation, creative workflows, and vibecoding."
keywords = [ "Moritz Lumetsberger", "entrepreneur", "3D animation", "FOOH", "DOOH", "rendersnek", "creative technologist", "AI automation", "vibecoding", "startup founder", "digital entrepreneurship" ]
author = "Moritz Lumetsberger"
images = ["/content/moritz-lumetsberger-2.jpg"]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[params.homeInfoParams]
Title = "I'm Moritz – Entrepreneur."
Content = "Entrepreneur who loves starting things and exploring bold ideas. Co-founder of rendersnek (3D animation studio) and FOOH.com (largest FOOH & CGI archive). Expert in AI automation, creative workflows, and vibecoding."

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/moritz-lumetsberger/"

[[params.socialIcons]]
name = "twitter"
url = "https://x.com/mo_snek"

[params.assets]
favicon = "/content/icon.jpg"
favicon16x16 = "/content/icon.jpg"
favicon32x32 = "/content/icon.jpg"
apple_touch_icon = "/content/icon.jpg"
safari_pinned_tab = "/content/icon.jpg"

[params.label]
text = "Home"
icon = ""
iconHeight = 35

[params.analytics.google]
SiteVerificationTag = ""

[params.analytics.bing]
SiteVerificationTag = ""

[params.analytics.yandex]
SiteVerificationTag = ""

[params.cover]
hidden = true
hiddenInList = true
hiddenInSingle = true

[params.editPost]
URL = ""
Text = ""
appendFilePath = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 20

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 30
