baseURL = 'https://lumetsberger.com'
languageCode = 'en-us'
title = 'Moritz Lumetsberger'
theme = 'PaperMod'

[params]
  # Site info
  description = "Personal website and blog of Moritz Lumetsberger"
  author = "Moritz Lumetsberger"
  
  # Profile mode configuration
  [params.profileMode]
    enabled = true
    title = "Moritz Lumetsberger"
    subtitle = "Personal website and blog"
  
  # Social links
  [[params.socialIcons]]
    name = "linkedin"
    title = "LinkedIn"
    url = "https://linkedin.com/in/lumetsberger"
  
  [[params.socialIcons]]
    name = "github"
    title = "GitHub"  
    url = "https://github.com/mrgoofman"
  
  [[params.socialIcons]]
    name = "email"
    title = "Email"
    url = "mailto:moritz@lumetsberger.com"

# Menu configuration
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  
  [[menu.main]]
    identifier = "about" 
    name = "About"
    url = "/about/"
    weight = 20
  
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 30

# Content configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Pagination
[params.pagination]
  paginatePages = 10
