baseURL = 'https://lumetsberger.com'
defaultContentLanguage = 'en'
theme = 'blowfish'

# pluralizeListTitles = false # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
paginate = 10
summaryLength = 0

googleAnalytics = "G-7WZS5M1WY6"

[imaging]
  anchor = 'Center'
  bgColor = '#ffffff'
  hint = 'photo'
  quality = 95
  resampleFilter = 'Box'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

[menu]
  [[menu.main]]
    name = "Blog"
    pageRef = "blog"
    weight = 20

  [[menu.main]]
    name = "About"
    pageRef = "about"
    weight = 30

[params]
  # theme
  version = "2.0"
  mode = "auto" # auto, light or dark
  
  # appearance
  colorScheme = "blowfish"
  showAppearanceSwitcher = true
  autoSwitchAppearance = true
  
  # behaviour
  enableSearch = true
  enableCodeCopy = true
  
  # article
  showDate = true
  showDateOnlyInArticle = false
  showDateUpdated = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = false
  showBreadcrumbs = false
  showTaxonomies = false
  showAuthorsBadges = false
  showWordCount = true
  showSummary = true
  sharingLinks = [ "linkedin", "twitter", "reddit", "pinterest", "facebook", "email", "whatsapp", "telegram"]

  [params.homepage]
    layout = "profile" # valid options: page, profile, hero, card, background, custom
    #homepageImage = "IMAGE.jpg" # used in: hero, and card
    showRecent = true
    showRecentItems = 5
    showMoreLink = true
    showMoreLinkDest = "/blog"
    cardView = true
    cardViewScreenWidth = false
    layoutBackgroundBlur = false # only used when layout equals background

  [params.article]
    showDate = true
    showViews = false
    showLikes = false
    showDateUpdated = false
    showAuthor = true
    showHero = true
    heroStyle = "basic" # valid options: basic, big, background, thumbAndBackground
    layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
    layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
    showBreadcrumbs = false
    showDraftLabel = true
    showEdit = false
    # editURL = "https://github.com/username/repo/"
    editAppendPath = true
    seriesOpened = false
    showHeadingAnchors = true
    showPagination = true
    invertPagination = false
    showReadingTime = true
    showTableOfContents = true
    # showRelatedContent = false
    # relatedContentLimit = 3
    showTaxonomies = false
    showAuthorsBadges = false
    showWordCount = true
    # sharingLinks = [ "linkedin", "twitter", "reddit", "pinterest", "facebook", "email", "whatsapp", "telegram"]
    showZenMode = true

  [params.list]
    showHero = true
    heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
    layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
    layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
    showBreadcrumbs = false
    showSummary = false
    showViews = false
    showLikes = false
    showTableOfContents = false
    showCards = true
    groupByYear = true
    cardView = false
    cardViewScreenWidth = false
    constrainItemsWidth = false

  [params.sitemap]
    excludedKinds = ["taxonomy", "term"]

  [params.taxonomy]
    showTermCount = true
    showHero = true
    heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
    showBreadcrumbs = false
    showViews = false
    showLikes = false
    showTableOfContents = true
    cardView = false

  [params.term]
    showHero = true
    heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
    showBreadcrumbs = false
    showViews = false
    showLikes = false
    showTableOfContents = true
    groupByYear = false
    cardView = false
    cardViewScreenWidth = false

  [params.firebase]
    # apiKey = "XXXXXX"
    # authDomain = "XXXXXX"
    # projectId = "XXXXXX"
    # storageBucket = "XXXXXX"
    # messagingSenderId = "XXXXXX"
    # appId = "XXXXXX"
    # measurementId = "XXXXXX"

  [params.fathomAnalytics]
    # site = "ABC12345"
    # domain = "llama.yoursite.com"

  [params.buymeacoffee]
    # identifier = ""
    # globalWidget = true
    # globalWidgetMessage = "Hello"
    # globalWidgetColor = "#FFDD00"
    # globalWidgetPosition = "Right"

  [params.verification]
    # google = ""
    # bing = ""
    # pinterest = ""
    # yandex = ""

[languages]
  [languages.en]
    languageCode = 'en'
    languageName = 'English'
    weight = 1
    title = 'Moritz Lumetsberger'

    [languages.en.params]
      displayName = 'EN'
      isoCode = 'en'
      rtl = false
      dateFormat = '2 January 2006'
      logo = '/content/icon.jpg'
      secondaryLogo = ''
      description = 'Entrepreneur who loves starting things and exploring bold ideas. Co-founder of rendersnek (3D animation studio) and FOOH.com (largest FOOH & CGI archive). Expert in AI automation, creative workflows, and vibecoding.'
      # copyright = 'Copy, _right?_ :thinking_face:'

      [languages.en.params.author]
        name = 'Moritz Lumetsberger'
        image = '/content/moritz-lumetsberger-2.jpg'
        headline = 'Entrepreneur • Creative Doer • Vibecoder'
        bio = 'Entrepreneur who loves starting things and exploring bold ideas. Co-founder of rendersnek and FOOH.com.'
        links = [
          { email = 'mailto:moritz@lumetsberger.com' },
          { link = 'https://lumetsberger.com' },
          { linkedin = 'https://www.linkedin.com/in/moritz-lumetsberger/' },
          { twitter = 'https://x.com/mo_snek' },
        ]